### ISSUE TITLE
Exclude some dir

### ISSUE THREAD

**Issue by andbad** [thiggy01/clone-linux#1]
You can add an option to exclude some dir on cloning process.
I make it mannually, adding the dir I want to exclude to rsync command and remove the size check.

**Comment by thiggy01** [comment]
@andbad I can easily add this function at the moment you are confirming the cloning process, but what do you mean by "remove the size check"?

**Comment by andbad** [comment]
The script check if the space on destination are enough to contain the source. With the current versione of the script, if you exclude some dir, you must bypass this check, because it count also the dir.
In my case: I had a system whith 4 disk in RAID, with a big folder inside. I moved the system files and dirs to a new SSD, but I leaved the "big dir" (a lot of TB) to old RAID. Of course, the script check failed because the size of the new SSD is too small of old RAID. So I excluded the "big dir" to not move, but I also must bypass the check.
I hope I explained myself.

**Comment by thiggy01** [comment]
@andbad Yes, now I understand your issue.
This will require a little more complicated coding, but I think it is not impossible.
Maybe I can even, instead of bypass the size check, change it to test with the new size that will be cloned.

**Comment by andbad** [comment]
@thiggy01 If you able to check the destinazion size compare to source size minus folder to exclude, I think that is the best result.

**Comment by thiggy01** [comment]
@andbad I ask you kindly to test this new version of my script to see if your issue is resolved.

**Comment by andbad** [comment]
Seems to work well. TY.

**Comment by thiggy01** [comment]
I'm glad it worked!
