### ISSUE TITLE
Cannot read partitions from disk with NVMe disks

### ISSUE THREAD

**Issue by alexlemaire** [thiggy01/clone-linux#2]
**Bug**

While trying to clone data from an HDD (regular disk partition syntax `/dev/sdbX`) to a new M.2 SSD (NVMe, disk partition syntax being `/dev/nvme0npX`) I had an error where `fdisk` was not able to list the partitions on the target disk.

**Cause**

After digging a bit in the script, I managed to get it to work by replacing the [following line](https://github.com/thiggy01/clone-ubuntu/blob/25e318da5ff083693f408201fd9848f3f2244d16/clone-ubuntu#L208) by this one:
```bash
    TargetDisk=$(echo "$TargetRootDev" | sed 's/p[0-9]\+$//')
```

This way instead of trimming only the number at the end of the partition to retrieve the disk name it also trimmed `p`.

I guess it would probably be more resilient if the updated regular expression was `/p\?[0-9]\+$//` instead to also handle a regular disk partition syntax.

If you want I can open a PR for this and you can have a look at it when you have some time!

**Comment by thiggy01** [comment]
@alexlemaire
Thanks for reporting this bug with NVMe disks!!!
Since this is just a simple regex change, I will simply add it to the code and give credits to you.
