### ISSUE TITLE
Failure to put files in EFI partition

### ISSUE THREAD

**Issue by ghost** [thiggy01/clone-linux#3]
System boots from original disk with UEFI
From /etc/fstab:
...
UUID=A346-6D27  /boot/efi       vfat    defaults      0       1
...
This line is repeated in cloned (target) /etc/fstab  . 
I created a 100MB partition at the beginning of the target disk, however it remained empty.
What should the contents of this partition be? And what other changes (e.g. in the target /etc/fstab) should there be?

Any additional information I can provide, my email is mike@rechtman.com

**Comment by sulibo** [comment]
> System boots from original disk with UEFI From /etc/fstab: ... UUID=A346-6D27 /boot/efi vfat defaults 0 1 ... This line is repeated in cloned (target) /etc/fstab . I created a 100MB partition at the beginning of the target disk, however it remained empty. What should the contents of this partition be? And what other changes (e.g. in the target /etc/fstab) should there be?
> 
> Any additional information I can provide, my email is [mike@rechtman.com](mailto:mike@rechtman.com)

I had the same problem/question. 

What I did: 
1. Create a partition for /boot/efi in the new ssd drive (size: 512 MiB, filesystem: fat32, flags: boot, esp)
2. Change the UUID  for /boot/efi in the cloned /etc/fstab accordingly 
3. Mount the 512MiB partition and copy all files in the current /boot/efi into it (I mounted it on `/mnt/bootefi`)
4. Change the uuid in the first line of the `/mnt/bootefi/EFI/ubuntu/grub.cfg` file:
    ```
    search.fs_uuid <your_target_root_uuid> root hd1,gpt2
    ```

Afterwards, the system is able to boot from the target ssd drive.

**Comment by ghost** [comment]
Following sulibo's advice I set the boot and esp flags on the 100MB partition, *before* running clone-ubuntu.
This caused files to be placed in that partition.
I did not check these files content (I mean to do that in the near future) but followed items 2,3,4 from the above comment. The system then booted from the target drive.
Perhaps the original creator of this program could do further testing and add more detailed instructions on cloning a UEFI disk...
Thanks for the clone-ubuntu program and for the helpful advice

**Comment by ghost** [comment]
Just tried cloning a UEFI disk with several other partitions (besides the linux and home partitions)
After setting the *boot* and *esp* flags the files in the boot parttition booted the target disk correctly.
However: I still had to correct the */etc/fstab* by editing the UUID for the target *home* partition, and marking unecessary lines as comments (Placing # in position one)
It would appear that setting the relevant flags on the EFI partition is sufficient. I think a note to that effect in the instructions screen would be useful.

**Comment by ghost** [comment]
Closing
